mymima/urls.py
from django.contrib import admin
from django.urls import path, include
from facts import views

app_name = "start"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('song/<int:id>', views.song, name="song"),
    path('search_results/', views.search_results, name="search_song"),
    path('artist_songs/<int:id>', views.artist_songs, name="name"),
    path('song/<str:letter>', views.song_start_with, name="song"),
    path('artist/<str:letter>', views.artist_start_with, name="artist"),
    path('', views.homepage_start, name="homepage"),
]

facts/models.py
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=100)

    def _str_(self):
        return self.name


class Song(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.PROTECT)
    title = models.CharField(max_length=200)

    def _str_(self):
        return self.title


class Fact(models.Model):
    song = models.ForeignKey(Song, on_delete=models.PROTECT, related_name='facts', blank=True, null=True)
    content = models.TextField()
    written_by = models.CharField(max_length=200, blank=True, null=True)

    def _str_(self):
        return self.content

facts/forms.py
from django import forms


class SearchString(forms.Form):
    search_results = forms.CharField(max_length=300)

facts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from facts.models import Song, Artist, Fact
from .forms import SearchString

from . import forms
from .forms import SearchString

letters_list = []
for i in range(1488, 1515):
    if i not in (1498, 1501, 1503, 1507, 1509):
        letters_list.append(chr(i))


def homepage_start(request):
    return render(request, "facts/homepage.html", {'letters_list': letters_list})


def base(request):
    return render(request, "facts/base.html", {'letters_list': letters_list})


def song(request, id):
    song = get_object_or_404(Song, id=id)
    return render(request, "facts/song_page.html", {'song': song})


def song_start_with(request, letter):
    list_of_songs = Song.objects.filter(title__startswith=letter)
    context = {
        'list_of_songs': list_of_songs,
    }
    return render(request, 'facts/song_start_with.html', context)


def artist_start_with(request, letter):
    list_of_artists = Artist.objects.filter(name__startswith=letter)
    context = {
        'list_of_artists': list_of_artists,
    }
    return render(request, 'facts/artist_start_with.html', context)


def artist_songs(request, id):
    artist = get_object_or_404(Artist, id=id)
    return render(request, 'facts/artist_songs.html', {"artist": artist})


def search_results(request):
    x = str(request.GET["search"])
    print(x)
    list_of_artists = Artist.objects.filter(name__contains=x)
    print(list_of_artists)
    list_of_songs = Song.objects.filter(title__contains=x)
    list_of_facts = Fact.objects.filter(content__contains=x)
    context = {'list_of_artists': list_of_artists,
               'list_of_songs': list_of_songs,
               'list_of_facts': list_of_facts,
               }

    return render(request, 'facts/list_songs_artists_facts.html', context)

facts/templates/facts/artist_songs.html
{% extends "facts/base.html" %}

{% block h2 %}
    {{ artist.name }}
{% endblock %}

{% block p %}
    {% for song in artist.song_set.all %}
        <p><a href="{% url 'song' song.id %}">{{ song }}</a> </p>
    {% endfor %}
{% endblock %}

facts/templates/facts/artist_start_with.html
{% extends "facts/base.html" %}

{% block h2 %}
    {{ song.title }}
{% endblock %}

{% block h4 %}
    {{ song.artist.name }}
{% endblock %}
{% block p %}
    {% for artist in list_of_artists %}
        <a href="{% url 'name' artist.id %}">{{ artist.name }}</a><br>
    {% endfor %}
{% endblock %}

facts/templates/facts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>מימה - </title>
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/logo-mima--rinat.gif' %}">
    <style>
        .header {
            height: 18vh;
        }

        body {

        }

        .all_letters {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: row;

        }

        .fact-table {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;

        }

        .fact1 {
            margin: 2px;
            padding: 4px;
            width: 60vw;
            background-color: #EDF3FE;
            height: content-box;
        }

        .fact2 {
            margin: 2px;
            padding: 4px;
            width: 60vw;
            background-color: #CBFFCC;
            height: content-box;
        }

        .base-header {
            border-bottom: 4px solid #800000;
        }

        .artist_letter, .song_letter {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: row;
        }

        .mima-logo {
            width: 17vw;
        }

        .mima-search {
            display: flex;
            justify-content: flex-start;
            align-items: center;
            flex-direction: row;
        }

    </style>
</head>
<body dir="rtl">
<div class="header">
    <div class="mima-search">
        <a class="logo" href="{% url 'homepage' %}"><img class="mima-logo" src="{% static 'images/logo5.gif' %}"
                                                         alt="My image"></a>
        <form action="/search_results" method="GET">
            {% csrf_token %}
            <input type="text" name="search" id="choice">
            <input type="submit" value="הולך מחפשת">
        </form>
    </div>
    <table>
        <div class="all_letters">
            <tr class="artist_letter">
                <td>
                    חפש לפי שם אומן:
                </td>
                {% for letter in letters_list %}
                    <td bgcolor="#CCFFCC"><a href="{% url 'artiststartwith' letter %}"> {{ letter }} </a></td>
                {% endfor %}
                <td>
                    חפש לפי שם שיר:
                </td>
                {% for letter in letters_list %}
                    <td bgcolor="#CCFFCC"><a href="{% url 'songstartwith' letter %}"> {{ letter }} </a></td>
                {% endfor %}
            </tr>
        </div>
    </table>
</div>
<div class="base-header">
</div>
<div class="main-page">
    <h1>{% block h1 %}{% endblock %}</h1>
    <h2>{% block h2 %}{% endblock %}</h2>
    <p>{% block p %}{% endblock %}</p>


</div>
</body>
</html>

facts/templates/facts/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>מימה - </title>
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/logo-mima--rinat.gif' %}">
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }

    </style>
</head>
<body dir="rtl">

<a class="logo" href="{% url 'homepage' %}"><img src="{% static 'images/logo5.gif' %}" alt="My image"></a>
<form action="/search_results" method="GET">
    {% csrf_token %}
    <input type="text" name="search" id="choice">
    <input type="submit" value="הולך מחפשת">
</form>
<table>
    <tr class="artist_letter">
        <p>
            חפש לפי שם אומן:
        </p>
        {% for letter in letters_list %}
            <td bgcolor="#CCFFCC"><a href="{% url 'artist' letter %}"> {{ letter }} </a></td>
        {% endfor %}
    </tr>
</table>
<table>
    <tr class="song_letter">
        <p>
            חפש לפי שם שיר:
        </p>
        {% for letter in letters_list %}
            <td bgcolor="#CCFFCC"><a href="{% url 'song' letter %}"> {{ letter }} </a></td>
        {% endfor %}
    </tr>
</table>
</body>
</html>

facts/templates/facts/list_songs_artists_facts.html
{% extends "facts/base.html" %}

{% block h2 %}
    {{ artist.name }}
{% endblock %}

{% block p %}
    <div>
        {#        {{% if list_of_artists != "<QuerySet []>" %}}#}
        <h2>תוצאות באמנים:</h2> <br>
        {% for artist in list_of_artists %}
            <div><a href="{% url 'name' artist.id %} ">{{ artist }}</a></div>
        {% endfor %}
        {#        {{% endif %}}#}
        {#        {{% if list_of_songs > 0 %}}#}
        <h2>תוצאות בשירים:</h2> <br>
        {% for song in list_of_songs.all %}
            <div><a href="{% url 'song' song.id %}">{{ song }}</a> - {{ song.artist }}</div>
        {% endfor %}
        {#        {{% endif %}}#}
        {#        {{% if list_of_facts > 0 %}}#}
        <h2>עובדות שקשורות:</h2>

        {% for fact in list_of_facts.all %}
            {#        {{ list_of_facts }}#}
            {#<a href="{% url 'song' song.id %}">{{ song }}</a>#}
            <div class="{% cycle 'fact1' 'fact2' %}"><a href="{% url 'song' fact.song.id %}">{{ fact.song }}</a>
                - {{ fact.song.artist }}<br>{{ fact }}</div>

        {% endfor %}
    </div>
{% endblock %}

facts/templates/facts/song_page.html
{% extends "facts/base.html" %}

{% block h1 %}
    {{ song.title }}
{% endblock %}

{% block h2 %}
    {{ song.artist.name }}
{% endblock %}

{% block p %}
    <div class="fact-table">
        {% for fact in song.facts.all %}
            <div class="{% cycle 'fact1' 'fact2' %}">{{ fact }}<br>נכתב ע״י{{ fact.written_by }}</div>
        {% endfor %}
    </div>
{% endblock %}

facts/templates/facts/song_start_with.html
{% extends "facts/base.html" %}

{% block h2 %}
    {{ song.title }}
{% endblock %}

{% block h4 %}
    {{ song.artist.name }}
{% endblock %}
{% block p %}
    {% for song in list_of_songs %}
        <a href="{% url 'song' song.id %}">{{ song.title }}</a><br>
    {% endfor %}
{% endblock %}